#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/version"

cd "$(dirname "$0")/.."
mkdir -p bin
echo "Building version $VERSION"
CGO_ENABLED=0 go build \
	-mod=vendor \
    -trimpath \
    -buildvcs=false \
    -ldflags "-buildid= -X main.VERSION=$VERSION -s -w" \
    -o bin/ipsec-vxlan-overlay-network .
CGO_ENABLED=0 go build \
	-mod=vendor \
    -trimpath \
    -buildvcs=false \
    -ldflags "-buildid= -X main.version=$VERSION -s -w" \
    -o bin/ipsec-vxlan-overlay-topology ./cmd/ipsec-vxlan-overlay-network
ln -sf ipsec-vxlan-overlay-network bin/ipsec-vxlan-connectivity-check
ln -sf ipsec-vxlan-overlay-network bin/connectivity-check
ln -sf ipsec-vxlan-overlay-network bin/rancher-net
